# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\진수\코딩\Python\git\BINARY-ESG\model\annotation_tool\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1236, 912)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_screen = QtWidgets.QLabel(self.centralwidget)
        self.Label_screen.setEnabled(True)
        self.Label_screen.setGeometry(QtCore.QRect(20, 10, 1024, 768))
        self.Label_screen.setObjectName("Label_screen")
        self.Button_dir = QtWidgets.QPushButton(self.centralwidget)
        self.Button_dir.setGeometry(QtCore.QRect(1060, 400, 151, 41))
        self.Button_dir.setTabletTracking(False)
        self.Button_dir.setObjectName("Button_dir")
        self.none_use = QtWidgets.QLabel(self.centralwidget)
        self.none_use.setGeometry(QtCore.QRect(50, 820, 56, 12))
        self.none_use.setObjectName("none_use")
        self.Label_object = QtWidgets.QLabel(self.centralwidget)
        self.Label_object.setGeometry(QtCore.QRect(90, 820, 131, 12))
        self.Label_object.setObjectName("Label_object")
        self.List_img = QtWidgets.QListWidget(self.centralwidget)
        self.List_img.setGeometry(QtCore.QRect(1060, 10, 150, 384))
        self.List_img.setTabletTracking(False)
        self.List_img.setFocusPolicy(QtCore.Qt.NoFocus)
        self.List_img.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.List_img.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.List_img.setObjectName("List_img")
        self.Button_save = QtWidgets.QPushButton(self.centralwidget)
        self.Button_save.setGeometry(QtCore.QRect(1060, 740, 151, 51))
        self.Button_save.setObjectName("Button_save")
        self.Button_load = QtWidgets.QPushButton(self.centralwidget)
        self.Button_load.setEnabled(False)
        self.Button_load.setGeometry(QtCore.QRect(1060, 800, 151, 41))
        self.Button_load.setTabletTracking(False)
        self.Button_load.setObjectName("Button_load")
        self.Label_message = QtWidgets.QLabel(self.centralwidget)
        self.Label_message.setGeometry(QtCore.QRect(50, 840, 191, 16))
        self.Label_message.setText("")
        self.Label_message.setObjectName("Label_message")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1236, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Label_screen.setText(_translate("MainWindow", "TextLabel"))
        self.Button_dir.setText(_translate("MainWindow", "이미지 경로"))
        self.none_use.setText(_translate("MainWindow", "객체 : "))
        self.Label_object.setText(_translate("MainWindow", "None"))
        self.Button_save.setText(_translate("MainWindow", "저장"))
        self.Button_load.setText(_translate("MainWindow", "불러오기"))
