spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/seat
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
  security:
    user:
      name: user
      password: 123

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  mustache:
    suffix: .html

logging:
  level:
    org.hibernate.sql: debug
#    org.springframework.web: debug
