spring:
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://3.38.78.1:3306/seat?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    # username: leegusrb
    # password: dlgusrb
    url: jdbc:h2:tcp://localhost/~/seat
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
  security:
    user:
      name: user
      password: 123

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  mustache:
    suffix: .html

#logging:
#  level:
#    org.hibernate.sql: debug
#    org.springframework.web: debug
